version: '3.3'

services:
  app:
    depends_on: [db]
    build: ./
    volumes:
      - ./src:/var/www/app/src
    ports:
      - 3000:3000 # main port
      - 9229:9229 # debuging port
    environment:
      - NODE_ENV=development
      - PORT=3000
    command: sh run_node.sh
  db:
    image: mysql:5.7 # upgrade this later
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    ports:
      - 3306:3306
    command: --disable-partition-engine-check