version: '3.3'

services:
  app:
    image: node-application
    build: ./
    volumes:
      - ./:/var/www/app
    ports:
      - 3000:3000
      - 9229:9229
    environment:
      - NODE_ENV=development
      - PORT=3000
    command: sh run_node.sh
  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: codebucks
      MYSQL_USER: coder
      MYSQL_PASSWORD: coder
    ports:
      - 3306:3306
